name: 'Check for file'
description: 'check for file existence'
inputs:
  file:  # file name
    description: 'file path'
    required: true
    default: '.github/CODEOWNERS'
outputs:
  file_exists: # output will be available to future steps
    description: 'if the file exists'
runs:
  using: 'node16'
  main: 'dist/index.js'
